//! Alert Q&A repository. Questions are threaded against a trade alert and
//! scoped to its room.
//!
//! Unlike the other repositories in this crate, these queries use the runtime
//! `sqlx::query_as` API rather than the compile-time `query!` macros: the
//! `.sqlx` offline cache is generated by `cargo sqlx prepare` against a live
//! database, which is not available here, so a freshly added macro query would
//! fail to compile offline. The runtime API needs no cache and is type-checked
//! by the `FromRow` impl below.

use anyhow::Context as _;
use domain::entities::Question;
use domain::{AlertId, QuestionId, RoomId, UserId};
use sqlx::PgPool;

/// Flat projection of a `questions` row in primitive types, decoded by `sqlx`
/// and then lifted into the strongly-typed domain [`Question`].
#[derive(sqlx::FromRow)]
struct QuestionRow {
    id: uuid::Uuid,
    alert_id: uuid::Uuid,
    room_id: uuid::Uuid,
    author_id: uuid::Uuid,
    author_name: String,
    body: String,
    answer: Option<String>,
    answered_by: Option<uuid::Uuid>,
    resolved: bool,
    created_at: time::OffsetDateTime,
    answered_at: Option<time::OffsetDateTime>,
}

impl From<QuestionRow> for Question {
    fn from(row: QuestionRow) -> Self {
        Self {
            id: QuestionId::from_uuid(row.id),
            alert_id: AlertId::from_uuid(row.alert_id),
            room_id: RoomId::from_uuid(row.room_id),
            author_id: UserId::from_uuid(row.author_id),
            author_name: row.author_name,
            body: row.body,
            answer: row.answer,
            answered_by: row.answered_by.map(UserId::from_uuid),
            resolved: row.resolved,
            created_at: row.created_at,
            answered_at: row.answered_at,
        }
    }
}

/// Whether an alert exists and belongs to the given room.
pub async fn alert_in_room(
    pool: &PgPool,
    room_id: RoomId,
    alert_id: AlertId,
) -> anyhow::Result<bool> {
    let exists: Option<(uuid::Uuid,)> =
        sqlx::query_as("SELECT id FROM alerts WHERE id = $1 AND room_id = $2")
            .bind(alert_id.as_uuid())
            .bind(room_id.as_uuid())
            .fetch_optional(pool)
            .await
            .context("check alert in room")?;
    Ok(exists.is_some())
}

/// Insert a question by `author_id` against an alert.
pub async fn create(
    pool: &PgPool,
    room_id: RoomId,
    alert_id: AlertId,
    author_id: UserId,
    body: &str,
) -> anyhow::Result<Question> {
    // CTE: INSERT then re-select with the users join (RETURNING can't JOIN), so the
    // row carries the author's display_name like list_for_alert.
    let row: QuestionRow = sqlx::query_as(
        "WITH ins AS ( \
             INSERT INTO questions (alert_id, room_id, author_id, body) \
             VALUES ($1, $2, $3, $4) \
             RETURNING id, alert_id, room_id, author_id, body, answer, \
                       answered_by, resolved, created_at, answered_at \
         ) \
         SELECT ins.id, ins.alert_id, ins.room_id, ins.author_id, ins.body, ins.answer, \
                ins.answered_by, ins.resolved, ins.created_at, ins.answered_at, \
                u.display_name AS author_name \
         FROM ins JOIN users u ON u.id = ins.author_id",
    )
    .bind(alert_id.as_uuid())
    .bind(room_id.as_uuid())
    .bind(author_id.as_uuid())
    .bind(body)
    .fetch_one(pool)
    .await
    .context("insert question")?;
    Ok(row.into())
}

/// List the questions for an alert (scoped to its room), oldest first.
pub async fn list_for_alert(
    pool: &PgPool,
    room_id: RoomId,
    alert_id: AlertId,
) -> anyhow::Result<Vec<Question>> {
    let rows: Vec<QuestionRow> = sqlx::query_as(
        "SELECT q.id, q.alert_id, q.room_id, q.author_id, q.body, q.answer, \
                q.answered_by, q.resolved, q.created_at, q.answered_at, \
                u.display_name AS author_name \
         FROM questions q JOIN users u ON u.id = q.author_id \
         WHERE q.alert_id = $1 AND q.room_id = $2 ORDER BY q.created_at ASC",
    )
    .bind(alert_id.as_uuid())
    .bind(room_id.as_uuid())
    .fetch_all(pool)
    .await
    .context("list questions")?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Answer and resolve a question. Scoped by `room_id`; returns `None` if no such
/// question exists in the room.
pub async fn resolve(
    pool: &PgPool,
    room_id: RoomId,
    question_id: QuestionId,
    answered_by: UserId,
    answer: &str,
) -> anyhow::Result<Option<Question>> {
    let row: Option<QuestionRow> = sqlx::query_as(
        "WITH upd AS ( \
             UPDATE questions \
             SET answer = $3, answered_by = $4, answered_at = now(), resolved = true \
             WHERE id = $1 AND room_id = $2 \
             RETURNING id, alert_id, room_id, author_id, body, answer, \
                       answered_by, resolved, created_at, answered_at \
         ) \
         SELECT upd.id, upd.alert_id, upd.room_id, upd.author_id, upd.body, upd.answer, \
                upd.answered_by, upd.resolved, upd.created_at, upd.answered_at, \
                u.display_name AS author_name \
         FROM upd JOIN users u ON u.id = upd.author_id",
    )
    .bind(question_id.as_uuid())
    .bind(room_id.as_uuid())
    .bind(answer)
    .bind(answered_by.as_uuid())
    .fetch_optional(pool)
    .await
    .context("resolve question")?;
    Ok(row.map(Into::into))
}
