//! Per-room file drive plus generic inline-image uploads. Bytes are stored on
//! local disk under the configured uploads directory; the database holds only
//! metadata. Listing and downloading are gated on [`Action::JoinRoom`]; managing
//! the drive (upload/delete) requires [`Action::ManageRoom`]; inline image
//! uploads require [`Action::PostMessage`].

use crate::auth::session::CurrentUser;
use crate::authorization::RoomContext;
use crate::db;
use crate::error::{AppError, AppResult};
use crate::state::AppState;
use axum::Json;
use axum::Router;
use axum::body::Body;
use axum::extract::{DefaultBodyLimit, Multipart, Path, Query, State};
use axum::http::header;
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use domain::entities::{File, FileCategory};
use domain::{Action, FileId, RoomId};
use serde::Deserialize;
use std::str::FromStr as _;

/// 25 MB cap on a single upload.
const MAX_UPLOAD_BYTES: usize = 25 * 1024 * 1024;

pub fn router() -> Router<AppState> {
    Router::new()
        .route("/api/rooms/{id}/files", get(list).post(upload))
        .route(
            "/api/rooms/{id}/files/{file_id}",
            axum::routing::delete(remove),
        )
        .route("/api/rooms/{id}/files/{file_id}/download", get(download))
        .route(
            "/api/rooms/{id}/uploads",
            axum::routing::post(upload_inline),
        )
        // Raise the request-body cap for this router's upload POSTs above axum's
        // 2 MB default — otherwise the 25 MB `read_file_part` check is unreachable
        // because the body is rejected at 2 MB first. +1 MB of headroom covers
        // multipart boundary/header overhead; the GET/DELETE routes carry no body.
        .layer(DefaultBodyLimit::max(MAX_UPLOAD_BYTES + 1024 * 1024))
}

#[derive(Deserialize)]
struct ListQuery {
    category: Option<String>,
}

async fn list(
    State(state): State<AppState>,
    CurrentUser(user): CurrentUser,
    Path(id): Path<RoomId>,
    Query(query): Query<ListQuery>,
) -> AppResult<Json<Vec<File>>> {
    let ctx = RoomContext::load(&state, &user, id).await?;
    ctx.ensure(&state, Action::JoinRoom).await?;

    let category = match query.category.as_deref() {
        Some(c) => Some(
            FileCategory::from_str(c)
                .map_err(|_| AppError::BadRequest("invalid category filter".into()))?,
        ),
        None => None,
    };
    Ok(Json(db::files::list(&state.db, id, category).await?))
}

/// One field read from a multipart upload: bytes plus the part's declared
/// filename and content type.
struct UploadedPart {
    filename: String,
    content_type: String,
    bytes: Vec<u8>,
}

/// Read the `file` field from a multipart body, enforcing the size cap. The
/// on-disk name is always generated by the server; the client filename is kept
/// only as display metadata.
async fn read_file_part(mut multipart: Multipart) -> AppResult<UploadedPart> {
    while let Some(field) = multipart
        .next_field()
        .await
        .map_err(|e| AppError::BadRequest(format!("invalid multipart body: {e}")))?
    {
        if field.name() != Some("file") {
            continue;
        }
        let filename = field.file_name().unwrap_or("file").to_owned();
        let content_type = field
            .content_type()
            .unwrap_or("application/octet-stream")
            .to_owned();
        let bytes = field
            .bytes()
            .await
            .map_err(|e| AppError::BadRequest(format!("failed to read upload: {e}")))?;
        if bytes.len() > MAX_UPLOAD_BYTES {
            return Err(AppError::PayloadTooLarge("file exceeds 25 MB limit".into()));
        }
        return Ok(UploadedPart {
            filename,
            content_type,
            bytes: bytes.to_vec(),
        });
    }
    Err(AppError::BadRequest("missing `file` field".into()))
}

/// Persist bytes to `{uploads_dir}/{uuid}` and insert the metadata row. The
/// storage name is a freshly generated UUID, never derived from client input.
async fn store(
    state: &AppState,
    room_id: RoomId,
    uploaded_by: domain::UserId,
    part: UploadedPart,
) -> AppResult<File> {
    let storage_name = uuid::Uuid::new_v4().to_string();
    let path = std::path::Path::new(&state.config.uploads_dir).join(&storage_name);
    tokio::fs::write(&path, &part.bytes)
        .await
        .map_err(|e| AppError::Internal(anyhow::Error::new(e).context("writing upload to disk")))?;

    let category = FileCategory::from_content_type(&part.content_type);
    let size = i64::try_from(part.bytes.len()).unwrap_or(i64::MAX);

    let result = db::files::create(
        &state.db,
        room_id,
        uploaded_by,
        &part.filename,
        &part.content_type,
        size,
        category,
        &storage_name,
    )
    .await;

    match result {
        Ok(file) => Ok(file),
        Err(err) => {
            // Best-effort cleanup so a failed insert does not orphan bytes.
            let _ = tokio::fs::remove_file(&path).await;
            Err(err.into())
        }
    }
}

async fn upload(
    State(state): State<AppState>,
    CurrentUser(user): CurrentUser,
    Path(id): Path<RoomId>,
    multipart: Multipart,
) -> AppResult<Json<File>> {
    let ctx = RoomContext::load(&state, &user, id).await?;
    ctx.ensure(&state, Action::ManageRoom).await?;

    let part = read_file_part(multipart).await?;
    let file = store(&state, id, user.user_id, part).await?;
    Ok(Json(file))
}

#[derive(serde::Serialize)]
struct InlineUploadResponse {
    url: String,
}

async fn upload_inline(
    State(state): State<AppState>,
    CurrentUser(user): CurrentUser,
    Path(id): Path<RoomId>,
    multipart: Multipart,
) -> AppResult<Json<InlineUploadResponse>> {
    let ctx = RoomContext::load(&state, &user, id).await?;
    ctx.ensure(&state, Action::PostMessage).await?;

    let part = read_file_part(multipart).await?;
    if FileCategory::from_content_type(&part.content_type) != FileCategory::Image {
        return Err(AppError::BadRequest(
            "only image uploads are allowed".into(),
        ));
    }
    let file = store(&state, id, user.user_id, part).await?;
    Ok(Json(InlineUploadResponse {
        url: file.download_url,
    }))
}

async fn download(
    State(state): State<AppState>,
    CurrentUser(user): CurrentUser,
    Path((id, file_id)): Path<(RoomId, FileId)>,
) -> AppResult<Response> {
    let ctx = RoomContext::load(&state, &user, id).await?;
    ctx.ensure(&state, Action::JoinRoom).await?;

    let (file, storage_name) = db::files::get_with_storage(&state.db, id, file_id)
        .await?
        .ok_or(AppError::NotFound)?;

    let path = std::path::Path::new(&state.config.uploads_dir).join(&storage_name);
    let bytes = tokio::fs::read(&path).await.map_err(|e| {
        AppError::Internal(anyhow::Error::new(e).context("reading upload from disk"))
    })?;

    let disposition = format!(
        "attachment; filename=\"{}\"",
        sanitize_filename(&file.filename)
    );
    Ok((
        [
            (header::CONTENT_TYPE, file.content_type),
            (header::CONTENT_DISPOSITION, disposition),
        ],
        Body::from(bytes),
    )
        .into_response())
}

async fn remove(
    State(state): State<AppState>,
    CurrentUser(user): CurrentUser,
    Path((id, file_id)): Path<(RoomId, FileId)>,
) -> AppResult<Json<serde_json::Value>> {
    let ctx = RoomContext::load(&state, &user, id).await?;
    ctx.ensure(&state, Action::ManageRoom).await?;

    let storage_name = db::files::delete(&state.db, id, file_id)
        .await?
        .ok_or(AppError::NotFound)?;

    let path = std::path::Path::new(&state.config.uploads_dir).join(&storage_name);
    if let Err(err) = tokio::fs::remove_file(&path).await {
        // The row is gone; a missing/unlinkable file is not fatal to the caller.
        tracing::warn!(error = ?err, %storage_name, "failed to unlink stored file");
    }
    Ok(Json(serde_json::json!({ "ok": true })))
}

/// Strip characters that would break a `Content-Disposition` header (quotes,
/// control chars, path separators) so a client filename cannot smuggle header
/// syntax.
fn sanitize_filename(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c == '"' || c == '\\' || c == '/' || c.is_control() {
                '_'
            } else {
                c
            }
        })
        .collect()
}
